# Generated by Django 4.2.7 on 2023-11-24 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('door_device', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='door',
            name='ip',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='door',
            name='name',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='door',
            name='number_door',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='door',
            name='status',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
