# Generated by Django 3.2.4 on 2023-12-09 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faqs', '0002_auto_20231209_1122'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='FAQCategory',
            new_name='FAQCategoria',
        ),
        migrations.RenameField(
            model_name='faq',
            old_name='category',
            new_name='categoria',
        ),
        migrations.RenameField(
            model_name='faq',
            old_name='question',
            new_name='descricao',
        ),
        migrations.RenameField(
            model_name='faq',
            old_name='answer',
            new_name='resposta',
        ),
        migrations.RenameField(
            model_name='faqcategoria',
            old_name='name',
            new_name='nome',
        ),
        migrations.RemoveField(
            model_name='faq',
            name='user',
        ),
        migrations.AddField(
            model_name='faq',
            name='pergunta',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
